name: Update Profile README

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches: [ main ]

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Try the more reliable anmol098/waka-readme-stats action first
      - name: Update README with WakaTime Stats (Primary)
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          LANG_COUNT: 10
          TIME_RANGE: last_7_days
          SHOW_TIMEZONE: false
          SHOW_EDITORS: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_LOC_CHART: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROFILE_VIEWS: false
          SHOW_SHORT_INFO: false
          SHOW_UPDATED_DATE: false
