name: WakaTime Backup Workflow

on:
  # Manual trigger only
  workflow_dispatch:

jobs:
  update-readme-backup:
    name: Update README with WakaTime (Backup)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # Backup method using original athul action with better config
      - name: Update README with WakaTime Stats (Backup)
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SHOW_TIME: true
          SHOW_TOTAL: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          COMMIT_MESSAGE: "📊 Updated WakaTime stats [backup method]" 
